# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER yyy

# 挂载目录  指定容器挂载点到宿主机自动生成的目录或其他容器
VOLUME /home/yyy
# 创建目录  新镜像构建成功以后创建指定目录
RUN mkdir -p /home/yyy
# 指定路径  # 设置工作目录
WORKDIR /home/yyy
# 复制jar文件到路径  拷贝到容器中的/home/yyy目录下
COPY ./jar/yyy-auth.jar /home/yyy/yyy-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","yyy-auth.jar"]

