# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER yyy

# 挂载目录
VOLUME /home/yyy
# 创建目录
RUN mkdir -p /home/yyy
# 指定路径
WORKDIR /home/yyy
# 复制jar文件到路径  拷贝到容器中的/home/yyy目录下
COPY ./jar/yyy-gateway.jar /home/yyy/yyy-gateway.jar
# 启动网关服务
ENTRYPOINT ["java","-jar","yyy-gateway.jar"]