# 基础镜像
FROM redis
# author
MAINTAINER yyy

# 挂载目录
VOLUME /home/yyy/redis
# 创建目录
RUN mkdir -p /home/yyy/redis
# 指定路径
WORKDIR /home/yyy/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/yyy/redis/redis.conf
################################以上可以完成一套流程从指定到创建到使用，如果想使用可以参照上面写法##################################

#这里copy过去的  在docker-compose都能在volumes: 看到再写一次挂载(包括我们自己新建的或者已经存在的，我们也可以按照这种写法  注意是可写可不写)