/*
 Navicat Premium Data Transfer

 Source Server         : yangyangyang
 Source Server Type    : MySQL
 Source Server Version : 80020 (8.0.20)
 Source Host           : localhost:3306
 Source Schema         : yyy-config

 Target Server Type    : MySQL
 Target Server Version : 80020 (8.0.20)
 File Encoding         : 65001

 Date: 15/01/2024 15:39:02
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for config_info
-- ----------------------------
DROP TABLE IF EXISTS `config_info`;
CREATE TABLE `config_info` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin COMMENT 'source user',
  `src_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'source ip',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' COMMENT '租户字段',
  `c_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `c_use` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `effect` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `c_schema` text CHARACTER SET utf8 COLLATE utf8_bin,
  `encrypted_data_key` text CHARACTER SET utf8 COLLATE utf8_bin COMMENT '秘钥',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_configinfo_datagrouptenant` (`data_id`,`group_id`,`tenant_id`)
) ENGINE=InnoDB AUTO_INCREMENT=245 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='config_info';

-- ----------------------------
-- Records of config_info
-- ----------------------------
BEGIN;
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (1, 'application-dev.yml', 'DEFAULT_GROUP', 'spring:\n  autoconfigure:\n    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure\n  mvc:\n    pathmatch:\n      matching-strategy: ant_path_matcher\n\n# feign 配置\nfeign:\n  sentinel:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n\n\n# tencent:\n#   SecretId: xxxxx\n#   SecretKey: xxxxx\n#   sms:\n#       AppKey: xxxxx\n#       SignName: xxxxx\n#       SdkAppId: xxxx\n#       TemplateID: xxxx\n\n\n\n# 本地文件上传    \nfile:\n    domain: http://127.0.0.1:9300\n    path: /Users/yyyz/Desktop/开源项目/uploadPath\n    prefix: \n\n\n\n# 阿里云配置\naliyun:\n  endpoint: oss-cn-hangzhou.aliyuncs.com\n  accessKeyId: LTAI5tN7V1nzWEezuLZ17dBC\n  accessKeySecret: jpTKv2wOZ9AMWh1aCbPI2UD9PZ1EQu\n  bucketName: aicloud888\n  # urlPrefix:\n', '4215e7e5be3e89e7c376e1216ee474d3', '2020-05-20 12:00:00', '2023-06-24 05:40:35', 'nacos', '0:0:0:0:0:0:0:1', '', '', '通用配置', 'null', 'null', 'yaml', '', '');
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (2, 'yyy-gateway-dev.yml', 'DEFAULT_GROUP', 'spring:\n  redis:\n    host: localhost\n    port: 6379\n    database: 0\n    timeout: 10000\n    #自定义属性\n    expire: 60000\n  cache:\n    type: redis\n    #设置缓存过期时间  防止缓存雪崩：大量key同时过期\n    redis:\n      time-to-live: 3600000\n      #指定默认前缀，如果此处我们指定了前缀则使用我们指定的前缀，推荐此处不指定前缀\n      #spring.cache.redis.key-prefix=CACHE_\n      #是否开始前缀，建议开启\n      use-key-prefix: true\n      #是否缓存空值，防止缓存穿透\n      cache-null-values: true\n  cloud:\n    gateway:\n      discovery:\n        locator:\n          lowerCaseServiceId: true\n          enabled: true\n      routes:\n        # 认证中心\n        - id: yyy-auth\n        # 路由的目标地址 lb就是负载均衡，后面跟服务名称\n          uri: lb://yyy-auth\n          predicates:  # 路由断言，也就是判断请求是否符合路由规则的条件\n          #当请求路径与 /auth/** 匹配时，该请求才能被转发到 http://localhost:9200 上(对应yyy-auth服务的端口9200)。\n            - Path=/auth/**\n          filters:\n            # 验证码处理\n            - CacheRequestFilter\n            - ValidateCodeFilter\n            #StripPrefix=1配置，表示网关转发到业务模块时候会自动截取前缀。\n            - StripPrefix=1\n        # 代码生成\n        - id: yyy-gen\n          uri: lb://yyy-gen\n          predicates:\n            - Path=/code/**\n          filters:\n            - StripPrefix=1\n        # 定时任务\n        - id: yyy-job\n          uri: lb://yyy-job\n          predicates:\n            - Path=/schedule/**\n          filters:\n            - StripPrefix=1\n        # 系统模块\n        - id: yyy-system\n          uri: lb://yyy-system\n          predicates:\n            - Path=/system/**\n          filters:\n            - StripPrefix=1\n            #黑名单配置\n            # - name: BlackListUrlFilter\n            #   args:\n            #     blacklistUrl:\n            #     - /user/list\n        # mq模块\n        - id: yyy-rabbit\n          uri: lb://yyy-rabbit\n          predicates:\n            - Path=/rabbit/**\n          filters:\n            - StripPrefix=1\n        # 测试模块\n        - id: yyy-test\n          uri: lb://yyy-test\n          predicates:\n            - Path=/test/**\n          filters:\n            - StripPrefix=1\n\n# 安全配置\nsecurity:\n  # 验证码\n  captcha:\n    enabled: true\n    type: math\n  # 防止XSS攻击\n  xss:\n    enabled: true\n    excludeUrls:\n      - /system/notice\n  # 不校验白名单 没有放行的会被网关拦截 过了网关又因为网关引入了security依赖，会强制你去登录，这是mvc同样放行了一些路径就起了作用\n  ignore:\n    whites:\n      - /auth/logout\n      - /auth/login\n      - /auth/register\n      - /*/v2/api-docs\n      - /csrf\n', '5904d4b03e57272d557170ab6766829c', '2020-05-14 14:17:55', '2024-01-02 02:24:49', 'nacos', '0:0:0:0:0:0:0:1', '', '', '网关模块', 'null', 'null', 'yaml', '', '');
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (3, 'yyy-auth-dev.yml', 'DEFAULT_GROUP', 'spring:\n  redis:\n    host: localhost\n    port: 6379\n    database: 0\n    timeout: 10000\n    #自定义属性\n    expire: 60000\n  cache:\n    type: redis\n    #设置缓存过期时间  防止缓存雪崩：大量key同时过期\n    redis:\n      time-to-live: 3600000\n      #指定默认前缀，如果此处我们指定了前缀则使用我们指定的前缀，推荐此处不指定前缀\n      #spring.cache.redis.key-prefix=CACHE_\n      #是否开始前缀，建议开启\n      use-key-prefix: true\n      #是否缓存空值，防止缓存穿透\n      cache-null-values: true\n# swagger配置\nswagger:\n  title: 权限模块接口文档\n  license: Powered By yyy\n  licenseUrl: https://yyy.vip', 'a1fd6bdf3bf3909e6b25ec2f9a2285c8', '2020-11-20 00:00:00', '2023-06-04 07:26:24', 'nacos', '0:0:0:0:0:0:0:1', '', '', '认证中心', 'null', 'null', 'yaml', '', '');
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (4, 'yyy-monitor-dev.yml', 'DEFAULT_GROUP', '# spring\nspring:\n  security:\n    user:\n      name: yyy\n      password: 123456\n  boot:\n    admin:\n      ui:\n        title: 服务状态监控\n', '871b68bf175d5e9da240f26c4ea41497', '2020-11-20 00:00:00', '2023-06-01 22:47:43', 'nacos', '0:0:0:0:0:0:0:1', '', '', '监控中心', 'null', 'null', 'yaml', '', '');
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (5, 'yyy-system-dev.yml', 'DEFAULT_GROUP', '# spring配置\nspring:\n  redis:\n    host: localhost\n    port: 6379\n    database: 0\n    timeout: 10000\n    #自定义属性\n    expire: 60000\n  cache:\n    type: redis\n    #设置缓存过期时间  防止缓存雪崩：大量key同时过期\n    redis:\n      time-to-live: 3600000\n      #指定默认前缀，如果此处我们指定了前缀则使用我们指定的前缀，推荐此处不指定前缀\n      #spring.cache.redis.key-prefix=CACHE_\n      #是否开始前缀，建议开启\n      use-key-prefix: true\n      #是否缓存空值，防止缓存穿透\n      cache-null-values: true\n  datasource:\n    druid:\n      stat-view-servlet:\n        enabled: true\n        loginUsername: admin\n        loginPassword: 123456\n    dynamic:\n      druid:\n        initial-size: 5\n        min-idle: 5\n        maxActive: 20\n        maxWait: 60000\n        timeBetweenEvictionRunsMillis: 60000\n        minEvictableIdleTimeMillis: 300000\n        validationQuery: SELECT 1 FROM DUAL\n        testWhileIdle: true\n        testOnBorrow: false\n        testOnReturn: false\n        poolPreparedStatements: true\n        maxPoolPreparedStatementPerConnectionSize: 20\n        filters: stat,slf4j\n        connectionProperties: druid.stat.mergeSql\\=true;druid.stat.slowSqlMillis\\=5000\n      datasource:\n          # 主库数据源\n          master:\n            driver-class-name: com.mysql.cj.jdbc.Driver\n            url: jdbc:mysql://localhost:3306/yyy-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n            username: root\n            password: lf18289339306\n          # 从库数据源\n          # slave:\n            # username: \n            # password: \n            # url: \n            # driver-class-name: \n\n# mybatis配置\n# mybatis:\n#     # 搜索指定包别名\n#     typeAliasesPackage: com.yyy.system\n#     # 配置mapper的扫描，找到所有的mapper.xml映射文件\n#     mapperLocations: classpath:mapper/**/*.xml\n\nmybatis-plus:\n  # 对应的 XML 文件位置\n  mapperLocations: classpath:mapper/**/*.xml\n  # 实体扫描，多个package用逗号或者分号分隔\n  typeAliasesPackage: com.yyy.system\n\n\n\n# swagger配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By yyy\n  licenseUrl: https://yyy.vip\n\n\n\nfileTemplate:\n  profile: fileTemplate/profile.jpg\n\n\n', 'a528ab6fcecef22ff43580c76ca1dbf5', '2020-11-20 00:00:00', '2023-06-09 11:10:41', 'nacos', '0:0:0:0:0:0:0:1', '', '', '系统模块', 'null', 'null', 'yaml', '', '');
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (6, 'yyy-gen-dev.yml', 'DEFAULT_GROUP', '# spring配置\nspring:\n  redis:\n    host: localhost\n    port: 6379\n    database: 0\n    timeout: 10000\n    #自定义属性\n    expire: 60000\n  cache:\n    type: redis\n    #设置缓存过期时间  防止缓存雪崩：大量key同时过期\n    redis:\n      time-to-live: 3600000\n      #指定默认前缀，如果此处我们指定了前缀则使用我们指定的前缀，推荐此处不指定前缀\n      #spring.cache.redis.key-prefix=CACHE_\n      #是否开始前缀，建议开启\n      use-key-prefix: true\n      #是否缓存空值，防止缓存穿透\n      cache-null-values: true\n  # datasource:\n  #   driver-class-name: com.mysql.cj.jdbc.Driver\n  #   url: jdbc:mysql://localhost:3306/ry-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n  #   username: root\n  #   password: lf18289339306\n  datasource:\n    druid:\n      stat-view-servlet:\n        enabled: true\n        loginUsername: admin\n        loginPassword: 123456\n    dynamic:\n      druid:\n        initial-size: 5\n        min-idle: 5\n        maxActive: 20\n        maxWait: 60000\n        timeBetweenEvictionRunsMillis: 60000\n        minEvictableIdleTimeMillis: 300000\n        validationQuery: SELECT 1 FROM DUAL\n        testWhileIdle: true\n        testOnBorrow: false\n        testOnReturn: false\n        poolPreparedStatements: true\n        maxPoolPreparedStatementPerConnectionSize: 20\n        filters: stat,slf4j\n        connectionProperties: druid.stat.mergeSql\\=true;druid.stat.slowSqlMillis\\=5000\n      datasource:\n          # 主库数据源\n          master:\n            driver-class-name: com.mysql.cj.jdbc.Driver\n            url: jdbc:mysql://localhost:3306/yyy-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n            username: root\n            password: lf18289339306\n          # 从库数据源\n          # slave:\n            # username: \n            # password: \n            # url: \n            # driver-class-name: \n\n# mybatis配置\n# mybatis:\n#     # 搜索指定包别名\n#     typeAliasesPackage: com.yyy.gen.domain\n#     # 配置mapper的扫描，找到所有的mapper.xml映射文件\n#     mapperLocations: classpath:mapper/**/*.xml\nmybatis-plus:\n  # 对应的 XML 文件位置\n  mapperLocations: classpath:mapper/**/*.xml\n  # 实体扫描，多个package用逗号或者分号分隔\n  typeAliasesPackage: com.yyy.gen\n\n\n# swagger配置\nswagger:\n  title: 代码生成接口文档\n  license: Powered By yyy\n  licenseUrl: https://yyy.vip\n\n# 代码生成\ngen:\n  # 作者\n  author: yyy\n  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool\n  packageName: com.yyy.system\n  # 自动去除表前缀，默认是false\n  autoRemovePre: false\n  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）\n  tablePrefix: sys_\n', 'c55868298258d0733f88ec696a7f3f24', '2020-11-20 00:00:00', '2023-06-04 07:26:41', 'nacos', '0:0:0:0:0:0:0:1', '', '', '代码生成', 'null', 'null', 'yaml', '', '');
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (7, 'yyy-job-dev.yml', 'DEFAULT_GROUP', '# spring配置\nspring:\n  redis:\n    host: localhost\n    port: 6379\n    database: 0\n    timeout: 10000\n    #自定义属性\n    expire: 60000\n  cache:\n    type: redis\n    #设置缓存过期时间  防止缓存雪崩：大量key同时过期\n    redis:\n      time-to-live: 3600000\n      #指定默认前缀，如果此处我们指定了前缀则使用我们指定的前缀，推荐此处不指定前缀\n      #spring.cache.redis.key-prefix=CACHE_\n      #是否开始前缀，建议开启\n      use-key-prefix: true\n      #是否缓存空值，防止缓存穿透\n      cache-null-values: true\n  # datasource:\n  #   driver-class-name: com.mysql.cj.jdbc.Driver\n  #   url: jdbc:mysql://localhost:3306/yyy-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n  #   username: root\n  #   password: lf18289339306\n  datasource:\n    druid:\n      stat-view-servlet:\n        enabled: true\n        loginUsername: admin\n        loginPassword: 123456\n    dynamic:\n      druid:\n        initial-size: 5\n        min-idle: 5\n        maxActive: 20\n        maxWait: 60000\n        timeBetweenEvictionRunsMillis: 60000\n        minEvictableIdleTimeMillis: 300000\n        validationQuery: SELECT 1 FROM DUAL\n        testWhileIdle: true\n        testOnBorrow: false\n        testOnReturn: false\n        poolPreparedStatements: true\n        maxPoolPreparedStatementPerConnectionSize: 20\n        filters: stat,slf4j\n        connectionProperties: druid.stat.mergeSql\\=true;druid.stat.slowSqlMillis\\=5000\n      datasource:\n          # 主库数据源\n          master:\n            driver-class-name: com.mysql.cj.jdbc.Driver\n            url: jdbc:mysql://localhost:3306/yyy-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n            username: root\n            password: lf18289339306\n          # 从库数据源\n          # slave:\n            # username: \n            # password: \n            # url: \n            # driver-class-name: \n\n\n\n# mybatis配置\n# mybatis:\n#     # 搜索指定包别名\n#     typeAliasesPackage: com.yyy.job.domain\n#     # 配置mapper的扫描，找到所有的mapper.xml映射文件\n#     mapperLocations: classpath:mapper/**/*.xml\nmybatis-plus:\n  # 对应的 XML 文件位置\n  mapperLocations: classpath:mapper/**/*.xml\n  # 实体扫描，多个package用逗号或者分号分隔\n  typeAliasesPackage: com.yyy.job\n\n\n# swagger配置\nswagger:\n  title: 定时任务接口文档\n  license: Powered By yyy\n  licenseUrl: https://yyy.vip\n', 'ffc3a0a83e9177427280febf19c98c4f', '2020-11-20 00:00:00', '2023-06-05 21:29:00', 'nacos', '0:0:0:0:0:0:0:1', '', '', '定时任务', 'null', 'null', 'yaml', '', '');
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (9, 'sentinel-yyy-gateway', 'DEFAULT_GROUP', '[\n    {\n        \"resource\": \"yyy-auth\",\n        \"count\": 500,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    },\n\n	{\n        \"resource\": \"yyy-gen\",\n        \"count\": 200,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    },\n	{\n        \"resource\": \"yyy-job\",\n        \"count\": 300,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    },\n{\n        \"resource\": \"yyy-system\",\n        \"count\": 500,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    }\n]', 'c214128c79dd840b5846ef884af9d239', '2020-11-20 00:00:00', '2024-01-02 03:20:09', 'nacos', '0:0:0:0:0:0:0:1', '', '', '限流策略', 'null', 'null', 'json', '', '');
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (54, 'yyy-rabbit-dev.yml', 'DEFAULT_GROUP', '# spring配置\nspring: \n    # datasource: \n    #     driver-class-name: com.mysql.cj.jdbc.Driver\n    #     url: jdbc:mysql://localhost:3306/yyy-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    #     username: root\n    #     password: lf18289339306\n    rabbitmq:\n        host: 127.0.0.1 # 服务器 IP\n        port: 5672 # 服务器端口\n        username: guest # 用户名\n        password: guest # 密码\n        virtual-host: / # 虚拟主机地址\n        publisher-confirm-type: CORRELATED\n        publisher-returns: true\n        template:\n            mandatory: true  #定义消息路由失败时的策略。true,则调用ReturnCallback;false,则直接丢弃消息\n        listener:   \n            simple:  #容器类型.simple简单理解为一对一；direct理解为一对多个消费者\n                prefetch: 10  #消费端限流，代表多少消息未被ack时，rabbitmq不会给消费者发送新的消息\n                acknowledge-mode: MANUAL\n                retry: \n                    max-attempts: 5 \n                    enabled: true\n                    initial-interval: 5000\n                default-requeue-rejected: false\n\n\n# mybatis配置\n# mybatis:\n#     # 搜索指定包别名\n#     typeAliasesPackage: com.yyy.rabbit\n#     # 配置mapper的扫描，找到所有的mapper.xml映射文件\n#     mapperLocations: classpath:mapper/**/*.xml\n\n\n# swagger配置\nswagger:\n  title: mq模块接口文档\n  license: Powered By yyy\n  licenseUrl: https://yyy.vip\n', '9d4847a9c871d318996cd86331719dee', '2022-10-07 01:12:40', '2023-09-21 04:36:20', 'nacos', '0:0:0:0:0:0:0:1', '', '', '消息中间件', '', '', 'yaml', '', NULL);
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (89, 'sentinel-yyy-system', 'DEFAULT_GROUP', '[\n        {\n        \"resource\": \"/test/getFileTemplate\",\n        \"count\": 1,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0  \n}\n]', '441800afe078bf24ec8760ecd22aaf6c', '2023-06-05 04:19:06', '2023-06-05 05:06:52', 'nacos', '0:0:0:0:0:0:0:1', '', '', '', '', '', 'json', '', NULL);
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (186, 'yyy-test-dev.yml', 'DEFAULT_GROUP', '# spring配置\nspring:\n  redis:\n    host: localhost\n    port: 6379\n    database: 0\n    timeout: 10000\n    #自定义属性\n    expire: 60000\n  cache:\n    type: redis\n    #设置缓存过期时间  防止缓存雪崩：大量key同时过期\n    redis:\n      time-to-live: 3600000\n      #指定默认前缀，如果此处我们指定了前缀则使用我们指定的前缀，推荐此处不指定前缀\n      #spring.cache.redis.key-prefix=CACHE_\n      #是否开始前缀，建议开启\n      use-key-prefix: true\n      #是否缓存空值，防止缓存穿透\n      cache-null-values: true\n  datasource:\n    druid:\n      stat-view-servlet:\n        enabled: true\n        loginUsername: admin\n        loginPassword: 123456\n    dynamic:\n      druid:\n        initial-size: 5\n        min-idle: 5\n        maxActive: 20\n        maxWait: 60000\n        timeBetweenEvictionRunsMillis: 60000\n        minEvictableIdleTimeMillis: 300000\n        validationQuery: SELECT 1 FROM DUAL\n        testWhileIdle: true\n        testOnBorrow: false\n        testOnReturn: false\n        poolPreparedStatements: true\n        maxPoolPreparedStatementPerConnectionSize: 20\n        filters: stat,slf4j\n        connectionProperties: druid.stat.mergeSql\\=true;druid.stat.slowSqlMillis\\=5000\n      datasource:\n          # 主库数据源\n          master:\n            driver-class-name: com.mysql.cj.jdbc.Driver\n            url: jdbc:mysql://localhost:3306/yyy-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n            username: root\n            password: lf18289339306\n          bank1:\n            driver-class-name: com.mysql.cj.jdbc.Driver\n            url: jdbc:mysql://localhost:3306/bank1?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n            username: root\n            password: lf18289339306\n          # 从库数据源\n          # slave:\n            # username: \n            # password: \n            # url: \n            # driver-class-name: \n\n# mybatis配置\n# mybatis:\n#     # 搜索指定包别名\n#     typeAliasesPackage: com.yyy.system\n#     # 配置mapper的扫描，找到所有的mapper.xml映射文件\n#     mapperLocations: classpath:mapper/**/*.xml\n\nmybatis-plus:\n  # 对应的 XML 文件位置\n  mapperLocations: classpath:mapper/**/*.xml\n  # 实体扫描，多个package用逗号或者分号分隔\n  typeAliasesPackage: com.yyy.test\n\n\n\n# swagger配置\nswagger:\n  title: 测试模块接口文档\n  license: Powered By yyy\n  licenseUrl: https://yyy.vip\n\n\n\nfileTemplate:\n  profile: fileTemplate/profile.jpg\n\n\n', '6f79914fe347798f38e98f92e76005f0', '2023-06-09 10:57:25', '2023-07-13 01:31:28', 'nacos', '0:0:0:0:0:0:0:1', '', '', '', '', '', 'yaml', '', NULL);
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (215, 'application-prod.yml', 'DEFAULT_GROUP', 'spring:\n  autoconfigure:\n    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure\n  mvc:\n    pathmatch:\n      matching-strategy: ant_path_matcher\n\n# feign 配置\nfeign:\n  sentinel:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n\n\n# tencent:\n#   SecretId: xxxxx\n#   SecretKey: xxxxx\n#   sms:\n#       AppKey: xxxxx\n#       SignName: xxxxx\n#       SdkAppId: xxxx\n#       TemplateID: xxxx\n\n\n\n# 本地文件上传    \nfile:\n    domain: http://127.0.0.1:9300\n    path: /Users/yyyz/Desktop/开源项目/uploadPath\n    prefix: \n\n\n\n# 阿里云配置\naliyun:\n  endpoint: oss-cn-hangzhou.aliyuncs.com\n  accessKeyId: LTAI5tN7V1nzWEezuLZ17dBC\n  accessKeySecret: jpTKv2wOZ9AMWh1aCbPI2UD9PZ1EQu\n  bucketName: aicloud888\n  # urlPrefix:\n', '4215e7e5be3e89e7c376e1216ee474d3', '2023-07-15 01:53:19', '2023-07-15 01:53:19', NULL, '0:0:0:0:0:0:0:1', '', '1015fa17-66f8-45dd-b604-9c2277edfe65', '通用配置', NULL, NULL, 'yaml', NULL, NULL);
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (216, 'yyy-gateway-prod.yml', 'DEFAULT_GROUP', 'spring:\n  redis:\n    host: yyy-redis\n    port: 6379\n    database: 0\n    timeout: 10000\n    #自定义属性\n    expire: 60000\n  cache:\n    type: redis\n    #设置缓存过期时间  防止缓存雪崩：大量key同时过期\n    redis:\n      time-to-live: 3600000\n      #指定默认前缀，如果此处我们指定了前缀则使用我们指定的前缀，推荐此处不指定前缀\n      #spring.cache.redis.key-prefix=CACHE_\n      #是否开始前缀，建议开启\n      use-key-prefix: true\n      #是否缓存空值，防止缓存穿透\n      cache-null-values: true\n  cloud:\n    gateway:\n      discovery:\n        locator:\n          lowerCaseServiceId: true\n          enabled: true\n      routes:\n        # 认证中心\n        - id: yyy-auth\n        # 路由的目标地址 lb就是负载均衡，后面跟服务名称\n          uri: lb://yyy-auth\n          predicates:  # 路由断言，也就是判断请求是否符合路由规则的条件\n          #当请求路径与 /auth/** 匹配时，该请求才能被转发到 http://localhost:9200 上(对应yyy-auth服务的端口9200)。\n            - Path=/auth/**\n          filters:\n            # 验证码处理\n            - CacheRequestFilter\n            - ValidateCodeFilter\n            #StripPrefix=1配置，表示网关转发到业务模块时候会自动截取前缀。\n            - StripPrefix=1\n        # 代码生成\n        - id: yyy-gen\n          uri: lb://yyy-gen\n          predicates:\n            - Path=/code/**\n          filters:\n            - StripPrefix=1\n        # 定时任务\n        - id: yyy-job\n          uri: lb://yyy-job\n          predicates:\n            - Path=/schedule/**\n          filters:\n            - StripPrefix=1\n        # 系统模块\n        - id: yyy-system\n          uri: lb://yyy-system\n          predicates:\n            - Path=/system/**\n          filters:\n            - StripPrefix=1\n            #黑名单配置\n            # - name: BlackListUrlFilter\n            #   args:\n            #     blacklistUrl:\n            #     - /user/list\n        # mq模块\n        - id: yyy-rabbit\n          uri: lb://yyy-rabbit\n          predicates:\n            - Path=/rabbit/**\n          filters:\n            - StripPrefix=1\n        # 测试模块\n        - id: yyy-test\n          uri: lb://yyy-test\n          predicates:\n            - Path=/test/**\n          filters:\n            - StripPrefix=1\n\n# 安全配置\nsecurity:\n  # 验证码\n  captcha:\n    enabled: false\n    type: math\n  # 防止XSS攻击\n  xss:\n    enabled: true\n    excludeUrls:\n      - /system/notice\n  # 不校验白名单\n  ignore:\n    whites:\n      - /auth/logout\n      - /auth/login\n      - /auth/register\n      - /*/v2/api-docs\n      - /csrf\n', '75de7c0e5897bc7bddc7d7e479d1a317', '2023-07-15 01:53:19', '2024-01-02 02:07:10', 'nacos', '0:0:0:0:0:0:0:1', '', '1015fa17-66f8-45dd-b604-9c2277edfe65', '网关模块', '', '', 'yaml', '', NULL);
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (217, 'yyy-auth-prod.yml', 'DEFAULT_GROUP', 'spring:\n  redis:\n    host: yyy-redis\n    port: 6379\n    database: 0\n    timeout: 10000\n    #自定义属性\n    expire: 60000\n  cache:\n    type: redis\n    #设置缓存过期时间  防止缓存雪崩：大量key同时过期\n    redis:\n      time-to-live: 3600000\n      #指定默认前缀，如果此处我们指定了前缀则使用我们指定的前缀，推荐此处不指定前缀\n      #spring.cache.redis.key-prefix=CACHE_\n      #是否开始前缀，建议开启\n      use-key-prefix: true\n      #是否缓存空值，防止缓存穿透\n      cache-null-values: true\n# swagger配置\nswagger:\n  title: 权限模块接口文档\n  license: Powered By yyy\n  licenseUrl: https://yyy.vip', 'ef067004b575336c2129bd4bf4a2094e', '2023-07-15 01:53:19', '2023-07-15 02:21:51', 'nacos', '0:0:0:0:0:0:0:1', '', '1015fa17-66f8-45dd-b604-9c2277edfe65', '认证中心', '', '', 'yaml', '', NULL);
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (218, 'yyy-monitor-prod.yml', 'DEFAULT_GROUP', '# spring\nspring:\n  security:\n    user:\n      name: yyy\n      password: 123456\n  boot:\n    admin:\n      ui:\n        title: 服务状态监控\n', '871b68bf175d5e9da240f26c4ea41497', '2023-07-15 01:53:19', '2023-07-15 01:53:19', NULL, '0:0:0:0:0:0:0:1', '', '1015fa17-66f8-45dd-b604-9c2277edfe65', '监控中心', NULL, NULL, 'yaml', NULL, NULL);
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (219, 'yyy-system-prod.yml', 'DEFAULT_GROUP', '# spring配置\nspring:\n  redis:\n    host: yyy-redis\n    port: 6379\n    database: 0\n    timeout: 10000\n    #自定义属性\n    expire: 60000\n  cache:\n    type: redis\n    #设置缓存过期时间  防止缓存雪崩：大量key同时过期\n    redis:\n      time-to-live: 3600000\n      #指定默认前缀，如果此处我们指定了前缀则使用我们指定的前缀，推荐此处不指定前缀\n      #spring.cache.redis.key-prefix=CACHE_\n      #是否开始前缀，建议开启\n      use-key-prefix: true\n      #是否缓存空值，防止缓存穿透\n      cache-null-values: true\n  datasource:\n    druid:\n      stat-view-servlet:\n        enabled: true\n        loginUsername: admin\n        loginPassword: 123456\n    dynamic:\n      druid:\n        initial-size: 5\n        min-idle: 5\n        maxActive: 20\n        maxWait: 60000\n        timeBetweenEvictionRunsMillis: 60000\n        minEvictableIdleTimeMillis: 300000\n        validationQuery: SELECT 1 FROM DUAL\n        testWhileIdle: true\n        testOnBorrow: false\n        testOnReturn: false\n        poolPreparedStatements: true\n        maxPoolPreparedStatementPerConnectionSize: 20\n        filters: stat,slf4j\n        connectionProperties: druid.stat.mergeSql\\=true;druid.stat.slowSqlMillis\\=5000\n      datasource:\n          # 主库数据源\n          master:\n            driver-class-name: com.mysql.cj.jdbc.Driver\n            url: jdbc:mysql://yyy-mysql:3306/yyy-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n            username: root\n            password: root\n          # 从库数据源\n          # slave:\n            # username: \n            # password: \n            # url: \n            # driver-class-name: \n\n# mybatis配置\n# mybatis:\n#     # 搜索指定包别名\n#     typeAliasesPackage: com.yyy.system\n#     # 配置mapper的扫描，找到所有的mapper.xml映射文件\n#     mapperLocations: classpath:mapper/**/*.xml\n\nmybatis-plus:\n  # 对应的 XML 文件位置\n  mapperLocations: classpath:mapper/**/*.xml\n  # 实体扫描，多个package用逗号或者分号分隔\n  typeAliasesPackage: com.yyy.system\n\n\n\n# swagger配置\nswagger:\n  title: 系统模块接口文档\n  license: Powered By yyy\n  licenseUrl: https://yyy.vip\n\n\n\nfileTemplate:\n  profile: fileTemplate/profile.jpg\n\n\n', '3b0c5f93683acd350bf201dc699f4509', '2023-07-15 01:53:19', '2023-07-15 02:22:28', 'nacos', '0:0:0:0:0:0:0:1', '', '1015fa17-66f8-45dd-b604-9c2277edfe65', '系统模块', '', '', 'yaml', '', NULL);
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (220, 'yyy-gen-prod.yml', 'DEFAULT_GROUP', '# spring配置\nspring:\n  redis:\n    host: yyy-redis\n    port: 6379\n    database: 0\n    timeout: 10000\n    #自定义属性\n    expire: 60000\n  cache:\n    type: redis\n    #设置缓存过期时间  防止缓存雪崩：大量key同时过期\n    redis:\n      time-to-live: 3600000\n      #指定默认前缀，如果此处我们指定了前缀则使用我们指定的前缀，推荐此处不指定前缀\n      #spring.cache.redis.key-prefix=CACHE_\n      #是否开始前缀，建议开启\n      use-key-prefix: true\n      #是否缓存空值，防止缓存穿透\n      cache-null-values: true\n  # datasource:\n  #   driver-class-name: com.mysql.cj.jdbc.Driver\n  #   url: jdbc:mysql://localhost:3306/ry-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n  #   username: root\n  #   password: lf18289339306\n  datasource:\n    druid:\n      stat-view-servlet:\n        enabled: true\n        loginUsername: admin\n        loginPassword: 123456\n    dynamic:\n      druid:\n        initial-size: 5\n        min-idle: 5\n        maxActive: 20\n        maxWait: 60000\n        timeBetweenEvictionRunsMillis: 60000\n        minEvictableIdleTimeMillis: 300000\n        validationQuery: SELECT 1 FROM DUAL\n        testWhileIdle: true\n        testOnBorrow: false\n        testOnReturn: false\n        poolPreparedStatements: true\n        maxPoolPreparedStatementPerConnectionSize: 20\n        filters: stat,slf4j\n        connectionProperties: druid.stat.mergeSql\\=true;druid.stat.slowSqlMillis\\=5000\n      datasource:\n          # 主库数据源\n          master:\n            driver-class-name: com.mysql.cj.jdbc.Driver\n            url: jdbc:mysql://yyy-mysql:3306/yyy-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n            username: root\n            password: root\n          # 从库数据源\n          # slave:\n            # username: \n            # password: \n            # url: \n            # driver-class-name: \n\n# mybatis配置\n# mybatis:\n#     # 搜索指定包别名\n#     typeAliasesPackage: com.yyy.gen.domain\n#     # 配置mapper的扫描，找到所有的mapper.xml映射文件\n#     mapperLocations: classpath:mapper/**/*.xml\nmybatis-plus:\n  # 对应的 XML 文件位置\n  mapperLocations: classpath:mapper/**/*.xml\n  # 实体扫描，多个package用逗号或者分号分隔\n  typeAliasesPackage: com.yyy.gen\n\n\n# swagger配置\nswagger:\n  title: 代码生成接口文档\n  license: Powered By yyy\n  licenseUrl: https://yyy.vip\n\n# 代码生成\ngen:\n  # 作者\n  author: yyy\n  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool\n  packageName: com.yyy.system\n  # 自动去除表前缀，默认是false\n  autoRemovePre: false\n  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）\n  tablePrefix: sys_\n', '679e08e0850bc47b6b4f52d60e5f809a', '2023-07-15 01:53:19', '2023-07-15 02:23:03', 'nacos', '0:0:0:0:0:0:0:1', '', '1015fa17-66f8-45dd-b604-9c2277edfe65', '代码生成', '', '', 'yaml', '', NULL);
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (221, 'yyy-job-prod.yml', 'DEFAULT_GROUP', '# spring配置\nspring:\n  redis:\n    host: yyy-redis\n    port: 6379\n    database: 0\n    timeout: 10000\n    #自定义属性\n    expire: 60000\n  cache:\n    type: redis\n    #设置缓存过期时间  防止缓存雪崩：大量key同时过期\n    redis:\n      time-to-live: 3600000\n      #指定默认前缀，如果此处我们指定了前缀则使用我们指定的前缀，推荐此处不指定前缀\n      #spring.cache.redis.key-prefix=CACHE_\n      #是否开始前缀，建议开启\n      use-key-prefix: true\n      #是否缓存空值，防止缓存穿透\n      cache-null-values: true\n  # datasource:\n  #   driver-class-name: com.mysql.cj.jdbc.Driver\n  #   url: jdbc:mysql://localhost:3306/yyy-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n  #   username: root\n  #   password: lf18289339306\n  datasource:\n    druid:\n      stat-view-servlet:\n        enabled: true\n        loginUsername: admin\n        loginPassword: 123456\n    dynamic:\n      druid:\n        initial-size: 5\n        min-idle: 5\n        maxActive: 20\n        maxWait: 60000\n        timeBetweenEvictionRunsMillis: 60000\n        minEvictableIdleTimeMillis: 300000\n        validationQuery: SELECT 1 FROM DUAL\n        testWhileIdle: true\n        testOnBorrow: false\n        testOnReturn: false\n        poolPreparedStatements: true\n        maxPoolPreparedStatementPerConnectionSize: 20\n        filters: stat,slf4j\n        connectionProperties: druid.stat.mergeSql\\=true;druid.stat.slowSqlMillis\\=5000\n      datasource:\n          # 主库数据源\n          master:\n            driver-class-name: com.mysql.cj.jdbc.Driver\n            url: jdbc:mysql://yyy-mysql:3306/yyy-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n            username: root\n            password: root\n          # 从库数据源\n          # slave:\n            # username: \n            # password: \n            # url: \n            # driver-class-name: \n\n\n\n# mybatis配置\n# mybatis:\n#     # 搜索指定包别名\n#     typeAliasesPackage: com.yyy.job.domain\n#     # 配置mapper的扫描，找到所有的mapper.xml映射文件\n#     mapperLocations: classpath:mapper/**/*.xml\nmybatis-plus:\n  # 对应的 XML 文件位置\n  mapperLocations: classpath:mapper/**/*.xml\n  # 实体扫描，多个package用逗号或者分号分隔\n  typeAliasesPackage: com.yyy.job\n\n\n# swagger配置\nswagger:\n  title: 定时任务接口文档\n  license: Powered By yyy\n  licenseUrl: https://yyy.vip\n', '74f8a09162f1a72a8b5c0e116318ffa2', '2023-07-15 01:53:19', '2023-07-15 02:23:32', 'nacos', '0:0:0:0:0:0:0:1', '', '1015fa17-66f8-45dd-b604-9c2277edfe65', '定时任务', '', '', 'yaml', '', NULL);
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (222, 'sentinel-yyy-gateway', 'DEFAULT_GROUP', '[\n    {\n        \"resource\": \"yyy-auth\",\n        \"count\": 500,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    },\n\n	{\n        \"resource\": \"yyy-gen\",\n        \"count\": 200,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    },\n	{\n        \"resource\": \"yyy-job\",\n        \"count\": 300,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    },\n{\n        \"resource\": \"yyy-system\",\n        \"count\": 500,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    }\n]', 'c214128c79dd840b5846ef884af9d239', '2023-07-15 01:53:19', '2024-01-02 03:21:14', 'nacos', '0:0:0:0:0:0:0:1', '', '1015fa17-66f8-45dd-b604-9c2277edfe65', '限流策略', '', '', 'json', '', NULL);
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (223, 'yyy-rabbit-prod.yml', 'DEFAULT_GROUP', '# spring配置\nspring: \n    # datasource: \n    #     driver-class-name: com.mysql.cj.jdbc.Driver\n    #     url: jdbc:mysql://localhost:3306/yyy-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n    #     username: root\n    #     password: lf18289339306\n    rabbitmq:\n        host: yyy-rabbitmq # 服务器 IP\n        port: 5672 # 服务器端口\n        username: guest # 用户名\n        password: guest # 密码\n        virtual-host: / # 虚拟主机地址\n        publisher-confirm-type: CORRELATED\n        publisher-returns: true\n        template:\n            mandatory: true  #定义消息路由失败时的策略。true,则调用ReturnCallback;false,则直接丢弃消息\n        listener:   \n            simple:  #容器类型.simple简单理解为一对一；direct理解为一对多个消费者\n                prefetch: 10  #消费端限流，代表多少消息未被ack时，rabbitmq不会给消费者发送新的消息\n                acknowledge-mode: MANUAL\n                retry: \n                    max-attempts: 5 \n                    enabled: true\n                    initial-interval: 5000\n                default-requeue-rejected: false\n\n\n# mybatis配置\n# mybatis:\n#     # 搜索指定包别名\n#     typeAliasesPackage: com.yyy.rabbit\n#     # 配置mapper的扫描，找到所有的mapper.xml映射文件\n#     mapperLocations: classpath:mapper/**/*.xml\n\n\n# swagger配置\nswagger:\n  title: mq模块接口文档\n  license: Powered By yyy\n  licenseUrl: https://yyy.vip\n', '3fb01d982f10ed6a91d575489da72013', '2023-07-15 01:53:19', '2023-07-15 02:24:12', 'nacos', '0:0:0:0:0:0:0:1', '', '1015fa17-66f8-45dd-b604-9c2277edfe65', '消息中间件', '', '', 'yaml', '', NULL);
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (224, 'sentinel-yyy-system', 'DEFAULT_GROUP', '[\n        {\n        \"resource\": \"/test/getFileTemplate\",\n        \"count\": 3,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0  \n}\n]', '942db6219d760686bab151e356789fe8', '2023-07-15 01:53:19', '2024-01-02 03:21:29', 'nacos', '0:0:0:0:0:0:0:1', '', '1015fa17-66f8-45dd-b604-9c2277edfe65', '', '', '', 'json', '', NULL);
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`, `encrypted_data_key`) VALUES (225, 'yyy-test-prod.yml', 'DEFAULT_GROUP', '# spring配置\nspring:\n  redis:\n    host: yyy-redis\n    port: 6379\n    database: 0\n    timeout: 10000\n    #自定义属性\n    expire: 60000\n  cache:\n    type: redis\n    #设置缓存过期时间  防止缓存雪崩：大量key同时过期\n    redis:\n      time-to-live: 3600000\n      #指定默认前缀，如果此处我们指定了前缀则使用我们指定的前缀，推荐此处不指定前缀\n      #spring.cache.redis.key-prefix=CACHE_\n      #是否开始前缀，建议开启\n      use-key-prefix: true\n      #是否缓存空值，防止缓存穿透\n      cache-null-values: true\n  datasource:\n    druid:\n      stat-view-servlet:\n        enabled: true\n        loginUsername: admin\n        loginPassword: 123456\n    dynamic:\n      druid:\n        initial-size: 5\n        min-idle: 5\n        maxActive: 20\n        maxWait: 60000\n        timeBetweenEvictionRunsMillis: 60000\n        minEvictableIdleTimeMillis: 300000\n        validationQuery: SELECT 1 FROM DUAL\n        testWhileIdle: true\n        testOnBorrow: false\n        testOnReturn: false\n        poolPreparedStatements: true\n        maxPoolPreparedStatementPerConnectionSize: 20\n        filters: stat,slf4j\n        connectionProperties: druid.stat.mergeSql\\=true;druid.stat.slowSqlMillis\\=5000\n      datasource:\n          # 主库数据源\n          master:\n            driver-class-name: com.mysql.cj.jdbc.Driver\n            url: jdbc:mysql://yyy-mysql:3306/yyy-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n            username: root\n            password: root\n          bank1:\n            driver-class-name: com.mysql.cj.jdbc.Driver\n            url: jdbc:mysql://yyy-mysql:3306/bank1?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\n            username: root\n            password: root\n          # 从库数据源\n          # slave:\n            # username: \n            # password: \n            # url: \n            # driver-class-name: \n\n# mybatis配置\n# mybatis:\n#     # 搜索指定包别名\n#     typeAliasesPackage: com.yyy.system\n#     # 配置mapper的扫描，找到所有的mapper.xml映射文件\n#     mapperLocations: classpath:mapper/**/*.xml\n\nmybatis-plus:\n  # 对应的 XML 文件位置\n  mapperLocations: classpath:mapper/**/*.xml\n  # 实体扫描，多个package用逗号或者分号分隔\n  typeAliasesPackage: com.yyy.test\n\n\n\n# swagger配置\nswagger:\n  title: 测试模块接口文档\n  license: Powered By yyy\n  licenseUrl: https://yyy.vip\n\n\n\nfileTemplate:\n  profile: fileTemplate/profile.jpg\n\n\n', '2c0320182e98c0d05d57930f936d639d', '2023-07-15 01:53:51', '2023-07-15 02:25:03', 'nacos', '0:0:0:0:0:0:0:1', '', '1015fa17-66f8-45dd-b604-9c2277edfe65', '', '', '', 'yaml', '', NULL);
COMMIT;

-- ----------------------------
-- Table structure for config_info_aggr
-- ----------------------------
DROP TABLE IF EXISTS `config_info_aggr`;
CREATE TABLE `config_info_aggr` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `datum_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'datum_id',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '内容',
  `gmt_modified` datetime NOT NULL COMMENT '修改时间',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_configinfoaggr_datagrouptenantdatum` (`data_id`,`group_id`,`tenant_id`,`datum_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='增加租户字段';

-- ----------------------------
-- Records of config_info_aggr
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for config_info_beta
-- ----------------------------
DROP TABLE IF EXISTS `config_info_beta`;
CREATE TABLE `config_info_beta` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `beta_ips` varchar(1024) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'betaIps',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin COMMENT 'source user',
  `src_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'source ip',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' COMMENT '租户字段',
  `encrypted_data_key` text CHARACTER SET utf8 COLLATE utf8_bin COMMENT '秘钥',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_configinfobeta_datagrouptenant` (`data_id`,`group_id`,`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='config_info_beta';

-- ----------------------------
-- Records of config_info_beta
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for config_info_tag
-- ----------------------------
DROP TABLE IF EXISTS `config_info_tag`;
CREATE TABLE `config_info_tag` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' COMMENT 'tenant_id',
  `tag_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin COMMENT 'source user',
  `src_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'source ip',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_configinfotag_datagrouptenanttag` (`data_id`,`group_id`,`tenant_id`,`tag_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='config_info_tag';

-- ----------------------------
-- Records of config_info_tag
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for config_tags_relation
-- ----------------------------
DROP TABLE IF EXISTS `config_tags_relation`;
CREATE TABLE `config_tags_relation` (
  `id` bigint NOT NULL COMMENT 'id',
  `tag_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_name',
  `tag_type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'tag_type',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' COMMENT 'tenant_id',
  `nid` bigint NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`nid`),
  UNIQUE KEY `uk_configtagrelation_configidtag` (`id`,`tag_name`,`tag_type`),
  KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='config_tag_relation';

-- ----------------------------
-- Records of config_tags_relation
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for group_capacity
-- ----------------------------
DROP TABLE IF EXISTS `group_capacity`;
CREATE TABLE `group_capacity` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Group ID，空字符表示整个集群',
  `quota` int unsigned NOT NULL DEFAULT '0' COMMENT '配额，0表示使用默认值',
  `usage` int unsigned NOT NULL DEFAULT '0' COMMENT '使用量',
  `max_size` int unsigned NOT NULL DEFAULT '0' COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int unsigned NOT NULL DEFAULT '0' COMMENT '聚合子配置最大个数，，0表示使用默认值',
  `max_aggr_size` int unsigned NOT NULL DEFAULT '0' COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int unsigned NOT NULL DEFAULT '0' COMMENT '最大变更历史数量',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_group_id` (`group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='集群、各Group容量信息表';

-- ----------------------------
-- Records of group_capacity
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for his_config_info
-- ----------------------------
DROP TABLE IF EXISTS `his_config_info`;
CREATE TABLE `his_config_info` (
  `id` bigint unsigned NOT NULL,
  `nid` bigint unsigned NOT NULL AUTO_INCREMENT,
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin,
  `src_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `op_type` char(10) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' COMMENT '租户字段',
  `encrypted_data_key` text CHARACTER SET utf8 COLLATE utf8_bin COMMENT '秘钥',
  PRIMARY KEY (`nid`),
  KEY `idx_gmt_create` (`gmt_create`),
  KEY `idx_gmt_modified` (`gmt_modified`),
  KEY `idx_did` (`data_id`)
) ENGINE=InnoDB AUTO_INCREMENT=303 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='多租户改造';

-- ----------------------------
-- Records of his_config_info
-- ----------------------------
BEGIN;
INSERT INTO `his_config_info` (`id`, `nid`, `data_id`, `group_id`, `app_name`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `op_type`, `tenant_id`, `encrypted_data_key`) VALUES (2, 295, 'yyy-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\n  redis:\n    host: localhost\n    port: 6379\n    database: 0\n    timeout: 10000\n    #自定义属性\n    expire: 60000\n  cache:\n    type: redis\n    #设置缓存过期时间  防止缓存雪崩：大量key同时过期\n    redis:\n      time-to-live: 3600000\n      #指定默认前缀，如果此处我们指定了前缀则使用我们指定的前缀，推荐此处不指定前缀\n      #spring.cache.redis.key-prefix=CACHE_\n      #是否开始前缀，建议开启\n      use-key-prefix: true\n      #是否缓存空值，防止缓存穿透\n      cache-null-values: true\n  cloud:\n    gateway:\n      discovery:\n        locator:\n          lowerCaseServiceId: true\n          enabled: true\n      routes:\n        # 认证中心\n        - id: yyy-auth\n          uri: lb://yyy-auth  # 路由的目标地址 lb就是负载均衡，后面跟服务名称\n          predicates:  # 路由断言，也就是判断请求是否符合路由规则的条件\n            - Path=/auth/**  #当请求路径与 /auth/** 匹配时，该请求才能被转发到 http://localhost:9200 上(对应yyy-auth服务的端口9200)。\n          filters:\n            # 验证码处理\n            - CacheRequestFilter\n            - ValidateCodeFilter\n            - StripPrefix=1     #StripPrefix=1配置，表示网关转发到业务模块时候会自动截取前缀。\n        # 代码生成\n        - id: yyy-gen\n          uri: lb://yyy-gen\n          predicates:\n            - Path=/code/**\n          filters:\n            - StripPrefix=1\n        # 定时任务\n        - id: yyy-job\n          uri: lb://yyy-job\n          predicates:\n            - Path=/schedule/**\n          filters:\n            - StripPrefix=1\n        # 系统模块\n        - id: yyy-system\n          uri: lb://yyy-system\n          predicates:\n            - Path=/system/**\n          filters:\n            - StripPrefix=1\n            #黑名单配置\n            # - name: BlackListUrlFilter\n            #   args:\n            #     blacklistUrl:\n            #     - /user/list\n        # mq模块\n        - id: yyy-rabbit\n          uri: lb://yyy-rabbit\n          predicates:\n            - Path=/rabbit/**\n          filters:\n            - StripPrefix=1\n        # 测试模块\n        - id: yyy-test\n          uri: lb://yyy-test\n          predicates:\n            - Path=/test/**\n          filters:\n            - StripPrefix=1\n\n# 安全配置\nsecurity:\n  # 验证码\n  captcha:\n    enabled: false\n    type: math\n  # 防止XSS攻击\n  xss:\n    enabled: true\n    excludeUrls:\n      - /system/notice\n  # 不校验白名单 没有放行的会被网关拦截 过了网关又因为网关引入了security依赖，会强制你去登录，这是mvc同样放行了一些路径就起了作用\n    whites:\n      - /auth/logout\n      - /auth/login\n      - /auth/register\n      - /*/v2/api-docs\n      - /csrf\n', '1f676605627fc67b16160028b8b84551', '2024-01-02 14:36:31', '2024-01-02 00:36:31', 'nacos', '0:0:0:0:0:0:0:1', 'U', '', NULL);
INSERT INTO `his_config_info` (`id`, `nid`, `data_id`, `group_id`, `app_name`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `op_type`, `tenant_id`, `encrypted_data_key`) VALUES (216, 296, 'yyy-gateway-prod.yml', 'DEFAULT_GROUP', '', 'spring:\n  redis:\n    host: yyy-redis\n    port: 6379\n    database: 0\n    timeout: 10000\n    #自定义属性\n    expire: 60000\n  cache:\n    type: redis\n    #设置缓存过期时间  防止缓存雪崩：大量key同时过期\n    redis:\n      time-to-live: 3600000\n      #指定默认前缀，如果此处我们指定了前缀则使用我们指定的前缀，推荐此处不指定前缀\n      #spring.cache.redis.key-prefix=CACHE_\n      #是否开始前缀，建议开启\n      use-key-prefix: true\n      #是否缓存空值，防止缓存穿透\n      cache-null-values: true\n  cloud:\n    gateway:\n      discovery:\n        locator:\n          lowerCaseServiceId: true\n          enabled: true\n      routes:\n        # 认证中心\n        - id: yyy-auth\n          uri: lb://yyy-auth  # 路由的目标地址 lb就是负载均衡，后面跟服务名称\n          predicates:  # 路由断言，也就是判断请求是否符合路由规则的条件\n            - Path=/auth/**  #当请求路径与 /auth/** 匹配时，该请求才能被转发到 http://localhost:9200 上(对应yyy-auth服务的端口9200)。\n          filters:\n            # 验证码处理\n            - CacheRequestFilter\n            - ValidateCodeFilter\n            - StripPrefix=1     #StripPrefix=1配置，表示网关转发到业务模块时候会自动截取前缀。\n        # 代码生成\n        - id: yyy-gen\n          uri: lb://yyy-gen\n          predicates:\n            - Path=/code/**\n          filters:\n            - StripPrefix=1\n        # 定时任务\n        - id: yyy-job\n          uri: lb://yyy-job\n          predicates:\n            - Path=/schedule/**\n          filters:\n            - StripPrefix=1\n        # 系统模块\n        - id: yyy-system\n          uri: lb://yyy-system\n          predicates:\n            - Path=/system/**\n          filters:\n            - StripPrefix=1\n            #黑名单配置\n            # - name: BlackListUrlFilter\n            #   args:\n            #     blacklistUrl:\n            #     - /user/list\n        # mq模块\n        - id: yyy-rabbit\n          uri: lb://yyy-rabbit\n          predicates:\n            - Path=/rabbit/**\n          filters:\n            - StripPrefix=1\n        # 测试模块\n        - id: yyy-test\n          uri: lb://yyy-test\n          predicates:\n            - Path=/test/**\n          filters:\n            - StripPrefix=1\n\n# 安全配置\nsecurity:\n  # 验证码\n  captcha:\n    enabled: false\n    type: math\n  # 防止XSS攻击\n  xss:\n    enabled: true\n    excludeUrls:\n      - /system/notice\n  # 不校验白名单\n  ignore:\n    whites:\n      - /auth/logout\n      - /auth/login\n      - /auth/register\n      - /*/v2/api-docs\n      - /csrf\n', 'e1bbf8b1762d85fbd59963ff238d86e9', '2024-01-02 16:07:10', '2024-01-02 02:07:10', 'nacos', '0:0:0:0:0:0:0:1', 'U', '1015fa17-66f8-45dd-b604-9c2277edfe65', NULL);
INSERT INTO `his_config_info` (`id`, `nid`, `data_id`, `group_id`, `app_name`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `op_type`, `tenant_id`, `encrypted_data_key`) VALUES (2, 297, 'yyy-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\n  redis:\n    host: localhost\n    port: 6379\n    database: 0\n    timeout: 10000\n    #自定义属性\n    expire: 60000\n  cache:\n    type: redis\n    #设置缓存过期时间  防止缓存雪崩：大量key同时过期\n    redis:\n      time-to-live: 3600000\n      #指定默认前缀，如果此处我们指定了前缀则使用我们指定的前缀，推荐此处不指定前缀\n      #spring.cache.redis.key-prefix=CACHE_\n      #是否开始前缀，建议开启\n      use-key-prefix: true\n      #是否缓存空值，防止缓存穿透\n      cache-null-values: true\n  cloud:\n    gateway:\n      discovery:\n        locator:\n          lowerCaseServiceId: true\n          enabled: true\n      routes:\n        # 认证中心\n        - id: yyy-auth\n        # 路由的目标地址 lb就是负载均衡，后面跟服务名称\n          uri: lb://yyy-auth\n          predicates:  # 路由断言，也就是判断请求是否符合路由规则的条件\n          #当请求路径与 /auth/** 匹配时，该请求才能被转发到 http://localhost:9200 上(对应yyy-auth服务的端口9200)。\n            - Path=/auth/**\n          filters:\n            # 验证码处理\n            - CacheRequestFilter\n            - ValidateCodeFilter\n            #StripPrefix=1配置，表示网关转发到业务模块时候会自动截取前缀。\n            - StripPrefix=1\n        # 代码生成\n        - id: yyy-gen\n          uri: lb://yyy-gen\n          predicates:\n            - Path=/code/**\n          filters:\n            - StripPrefix=1\n        # 定时任务\n        - id: yyy-job\n          uri: lb://yyy-job\n          predicates:\n            - Path=/schedule/**\n          filters:\n            - StripPrefix=1\n        # 系统模块\n        - id: yyy-system\n          uri: lb://yyy-system\n          predicates:\n            - Path=/system/**\n          filters:\n            - StripPrefix=1\n            #黑名单配置\n            # - name: BlackListUrlFilter\n            #   args:\n            #     blacklistUrl:\n            #     - /user/list\n        # mq模块\n        - id: yyy-rabbit\n          uri: lb://yyy-rabbit\n          predicates:\n            - Path=/rabbit/**\n          filters:\n            - StripPrefix=1\n        # 测试模块\n        - id: yyy-test\n          uri: lb://yyy-test\n          predicates:\n            - Path=/test/**\n          filters:\n            - StripPrefix=1\n\n# 安全配置\nsecurity:\n  # 验证码\n  captcha:\n    enabled: false\n    type: math\n  # 防止XSS攻击\n  xss:\n    enabled: true\n    excludeUrls:\n      - /system/notice\n  # 不校验白名单 没有放行的会被网关拦截 过了网关又因为网关引入了security依赖，会强制你去登录，这是mvc同样放行了一些路径就起了作用\n    whites:\n      - /auth/logout\n      - /auth/login\n      - /auth/register\n      - /*/v2/api-docs\n      - /csrf\n', '6fab6e875f111cf41f40c5289f046a17', '2024-01-02 16:08:24', '2024-01-02 02:08:24', 'nacos', '0:0:0:0:0:0:0:1', 'U', '', NULL);
INSERT INTO `his_config_info` (`id`, `nid`, `data_id`, `group_id`, `app_name`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `op_type`, `tenant_id`, `encrypted_data_key`) VALUES (2, 298, 'yyy-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\n  redis:\n    host: localhost\n    port: 6379\n    database: 0\n    timeout: 10000\n    #自定义属性\n    expire: 60000\n  cache:\n    type: redis\n    #设置缓存过期时间  防止缓存雪崩：大量key同时过期\n    redis:\n      time-to-live: 3600000\n      #指定默认前缀，如果此处我们指定了前缀则使用我们指定的前缀，推荐此处不指定前缀\n      #spring.cache.redis.key-prefix=CACHE_\n      #是否开始前缀，建议开启\n      use-key-prefix: true\n      #是否缓存空值，防止缓存穿透\n      cache-null-values: true\n  cloud:\n    gateway:\n      discovery:\n        locator:\n          lowerCaseServiceId: true\n          enabled: true\n      routes:\n        # 认证中心\n        - id: yyy-auth\n        # 路由的目标地址 lb就是负载均衡，后面跟服务名称\n          uri: lb://yyy-auth\n          predicates:  # 路由断言，也就是判断请求是否符合路由规则的条件\n          #当请求路径与 /auth/** 匹配时，该请求才能被转发到 http://localhost:9200 上(对应yyy-auth服务的端口9200)。\n            - Path=/auth/**\n          filters:\n            # 验证码处理\n            - CacheRequestFilter\n            - ValidateCodeFilter\n            #StripPrefix=1配置，表示网关转发到业务模块时候会自动截取前缀。\n            - StripPrefix=1\n        # 代码生成\n        - id: yyy-gen\n          uri: lb://yyy-gen\n          predicates:\n            - Path=/code/**\n          filters:\n            - StripPrefix=1\n        # 定时任务\n        - id: yyy-job\n          uri: lb://yyy-job\n          predicates:\n            - Path=/schedule/**\n          filters:\n            - StripPrefix=1\n        # 系统模块\n        - id: yyy-system\n          uri: lb://yyy-system\n          predicates:\n            - Path=/system/**\n          filters:\n            - StripPrefix=1\n            #黑名单配置\n            # - name: BlackListUrlFilter\n            #   args:\n            #     blacklistUrl:\n            #     - /user/list\n        # mq模块\n        - id: yyy-rabbit\n          uri: lb://yyy-rabbit\n          predicates:\n            - Path=/rabbit/**\n          filters:\n            - StripPrefix=1\n        # 测试模块\n        - id: yyy-test\n          uri: lb://yyy-test\n          predicates:\n            - Path=/test/**\n          filters:\n            - StripPrefix=1\n\n# 安全配置\nsecurity:\n  # 验证码\n  captcha:\n    enabled: false\n    type: math\n  # 防止XSS攻击\n  xss:\n    enabled: true\n    excludeUrls:\n      - /system/notice\n  # 不校验白名单 没有放行的会被网关拦截 过了网关又因为网关引入了security依赖，会强制你去登录，这是mvc同样放行了一些路径就起了作用\n    whites:\n      - /auth/logout\n      - /auth/login\n      - /auth/register\n      - /*/v2/api-docs\n      - /csrf\n', '6fab6e875f111cf41f40c5289f046a17', '2024-01-02 16:11:14', '2024-01-02 02:11:14', 'nacos', '0:0:0:0:0:0:0:1', 'U', '', NULL);
INSERT INTO `his_config_info` (`id`, `nid`, `data_id`, `group_id`, `app_name`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `op_type`, `tenant_id`, `encrypted_data_key`) VALUES (2, 299, 'yyy-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\n  redis:\n    host: localhost\n    port: 6379\n    database: 0\n    timeout: 10000\n    #自定义属性\n    expire: 60000\n  cache:\n    type: redis\n    #设置缓存过期时间  防止缓存雪崩：大量key同时过期\n    redis:\n      time-to-live: 3600000\n      #指定默认前缀，如果此处我们指定了前缀则使用我们指定的前缀，推荐此处不指定前缀\n      #spring.cache.redis.key-prefix=CACHE_\n      #是否开始前缀，建议开启\n      use-key-prefix: true\n      #是否缓存空值，防止缓存穿透\n      cache-null-values: true\n  cloud:\n    gateway:\n      discovery:\n        locator:\n          lowerCaseServiceId: true\n          enabled: true\n      routes:\n        # 认证中心\n        - id: yyy-auth\n        # 路由的目标地址 lb就是负载均衡，后面跟服务名称\n          uri: lb://yyy-auth\n          predicates:  # 路由断言，也就是判断请求是否符合路由规则的条件\n          #当请求路径与 /auth/** 匹配时，该请求才能被转发到 http://localhost:9200 上(对应yyy-auth服务的端口9200)。\n            - Path=/auth/**\n          filters:\n            # 验证码处理\n            - CacheRequestFilter\n            - ValidateCodeFilter\n            #StripPrefix=1配置，表示网关转发到业务模块时候会自动截取前缀。\n            - StripPrefix=1\n        # 代码生成\n        - id: yyy-gen\n          uri: lb://yyy-gen\n          predicates:\n            - Path=/code/**\n          filters:\n            - StripPrefix=1\n        # 定时任务\n        - id: yyy-job\n          uri: lb://yyy-job\n          predicates:\n            - Path=/schedule/**\n          filters:\n            - StripPrefix=1\n        # 系统模块\n        - id: yyy-system\n          uri: lb://yyy-system\n          predicates:\n            - Path=/system/**\n          filters:\n            - StripPrefix=1\n            #黑名单配置\n            # - name: BlackListUrlFilter\n            #   args:\n            #     blacklistUrl:\n            #     - /user/list\n        # mq模块\n        - id: yyy-rabbit\n          uri: lb://yyy-rabbit\n          predicates:\n            - Path=/rabbit/**\n          filters:\n            - StripPrefix=1\n        # 测试模块\n        - id: yyy-test\n          uri: lb://yyy-test\n          predicates:\n            - Path=/test/**\n          filters:\n            - StripPrefix=1\n\n# 安全配置\nsecurity:\n  # 验证码\n  captcha:\n    enabled: true\n    type: math\n  # 防止XSS攻击\n  xss:\n    enabled: true\n    excludeUrls:\n      - /system/notice\n  # 不校验白名单 没有放行的会被网关拦截 过了网关又因为网关引入了security依赖，会强制你去登录，这是mvc同样放行了一些路径就起了作用\n    whites:\n      - /auth/logout\n      - /auth/login\n      - /auth/register\n      - /*/v2/api-docs\n      - /csrf\n', '93f682f845ba50144d2aac659f6e839d', '2024-01-02 16:24:48', '2024-01-02 02:24:49', 'nacos', '0:0:0:0:0:0:0:1', 'U', '', NULL);
INSERT INTO `his_config_info` (`id`, `nid`, `data_id`, `group_id`, `app_name`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `op_type`, `tenant_id`, `encrypted_data_key`) VALUES (9, 300, 'sentinel-yyy-gateway', 'DEFAULT_GROUP', '', '[\n    {\n        \"resource\": \"yyy-auth\",\n        \"count\": 500,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    },\n\n	{\n        \"resource\": \"yyy-gen\",\n        \"count\": 200,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    },\n	{\n        \"resource\": \"yyy-job\",\n        \"count\": 300,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    },\n{\n        \"resource\": \"yyy-system\",\n        \"count\": 1,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    }\n]', '73b24229e0fda2c52eae76963a3662cb', '2024-01-02 17:20:09', '2024-01-02 03:20:09', 'nacos', '0:0:0:0:0:0:0:1', 'U', '', NULL);
INSERT INTO `his_config_info` (`id`, `nid`, `data_id`, `group_id`, `app_name`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `op_type`, `tenant_id`, `encrypted_data_key`) VALUES (222, 301, 'sentinel-yyy-gateway', 'DEFAULT_GROUP', '', '[\n    {\n        \"resource\": \"yyy-auth\",\n        \"count\": 500,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    },\n\n	{\n        \"resource\": \"yyy-gen\",\n        \"count\": 200,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    },\n	{\n        \"resource\": \"yyy-job\",\n        \"count\": 300,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    },\n{\n        \"resource\": \"yyy-system\",\n        \"count\": 1,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0\n    }\n]', '73b24229e0fda2c52eae76963a3662cb', '2024-01-02 17:21:13', '2024-01-02 03:21:14', 'nacos', '0:0:0:0:0:0:0:1', 'U', '1015fa17-66f8-45dd-b604-9c2277edfe65', NULL);
INSERT INTO `his_config_info` (`id`, `nid`, `data_id`, `group_id`, `app_name`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `op_type`, `tenant_id`, `encrypted_data_key`) VALUES (224, 302, 'sentinel-yyy-system', 'DEFAULT_GROUP', '', '[\n        {\n        \"resource\": \"/test/getFileTemplate\",\n        \"count\": 1,\n        \"grade\": 1,\n        \"limitApp\": \"default\",\n        \"strategy\": 0,\n        \"controlBehavior\": 0  \n}\n]', '441800afe078bf24ec8760ecd22aaf6c', '2024-01-02 17:21:29', '2024-01-02 03:21:29', 'nacos', '0:0:0:0:0:0:0:1', 'U', '1015fa17-66f8-45dd-b604-9c2277edfe65', NULL);
COMMIT;

-- ----------------------------
-- Table structure for permissions
-- ----------------------------
DROP TABLE IF EXISTS `permissions`;
CREATE TABLE `permissions` (
  `role` varchar(50) NOT NULL,
  `resource` varchar(255) NOT NULL,
  `action` varchar(8) NOT NULL,
  UNIQUE KEY `uk_role_permission` (`role`,`resource`,`action`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----------------------------
-- Records of permissions
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for roles
-- ----------------------------
DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles` (
  `username` varchar(50) NOT NULL,
  `role` varchar(50) NOT NULL,
  UNIQUE KEY `idx_user_role` (`username`,`role`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----------------------------
-- Records of roles
-- ----------------------------
BEGIN;
INSERT INTO `roles` (`username`, `role`) VALUES ('nacos', 'ROLE_ADMIN');
COMMIT;

-- ----------------------------
-- Table structure for tenant_capacity
-- ----------------------------
DROP TABLE IF EXISTS `tenant_capacity`;
CREATE TABLE `tenant_capacity` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Tenant ID',
  `quota` int unsigned NOT NULL DEFAULT '0' COMMENT '配额，0表示使用默认值',
  `usage` int unsigned NOT NULL DEFAULT '0' COMMENT '使用量',
  `max_size` int unsigned NOT NULL DEFAULT '0' COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int unsigned NOT NULL DEFAULT '0' COMMENT '聚合子配置最大个数',
  `max_aggr_size` int unsigned NOT NULL DEFAULT '0' COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int unsigned NOT NULL DEFAULT '0' COMMENT '最大变更历史数量',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='租户容量信息表';

-- ----------------------------
-- Records of tenant_capacity
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for tenant_info
-- ----------------------------
DROP TABLE IF EXISTS `tenant_info`;
CREATE TABLE `tenant_info` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `kp` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'kp',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' COMMENT 'tenant_id',
  `tenant_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' COMMENT 'tenant_name',
  `tenant_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'tenant_desc',
  `create_source` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'create_source',
  `gmt_create` bigint NOT NULL COMMENT '创建时间',
  `gmt_modified` bigint NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_info_kptenantid` (`kp`,`tenant_id`),
  KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='tenant_info';

-- ----------------------------
-- Records of tenant_info
-- ----------------------------
BEGIN;
INSERT INTO `tenant_info` (`id`, `kp`, `tenant_id`, `tenant_name`, `tenant_desc`, `create_source`, `gmt_create`, `gmt_modified`) VALUES (2, '1', '1015fa17-66f8-45dd-b604-9c2277edfe65', 'prod', '生产环境', 'nacos', 1689403404711, 1689403404711);
COMMIT;

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `username` varchar(50) NOT NULL,
  `password` varchar(500) NOT NULL,
  `enabled` tinyint(1) NOT NULL,
  PRIMARY KEY (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----------------------------
-- Records of users
-- ----------------------------
BEGIN;
INSERT INTO `users` (`username`, `password`, `enabled`) VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', 1);
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
