# 基础镜像
FROM nginx
# author
MAINTAINER yyy

# 挂载目录
VOLUME /home/yyy/projects/yyy-ui
# 创建目录
RUN mkdir -p /home/yyy/projects/yyy-ui
# 指定路径
WORKDIR /home/yyy/projects/yyy-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/yyy/projects/yyy-ui
